service: album-covers

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

functions:
  getAlbum:
    handler: handler.getAlbum
    description: Searchs spotify for the album of the given track
